### ISSUE TITLE
组件内部可以调用页面上的js变量吗？

### ISSUE THREAD

**Issue by regboy8** [mipengine/mip-extensions-platform#10]
组件内部可以直接调用页面上的js变量吗？不行的话，通过什么方法可以调用页面上的js变量？

**Comment by wupengFEX** [comment]
@regboy8 可以调用绑定在window上的变量，但不推荐这样绑定数据。有什么需求需要这样来获取变量？

**Comment by regboy8** [comment]
谢了，我本来是想兼容旧的页面，现在我直接把变量写入到组件中，通过组件来获取外部变量了

**Comment by wupengFEX** [comment]
LGTM
