### ISSUE TITLE
关于组件引用自定义库JS的讨论

### ISSUE THREAD

**Issue by jennyliang220** [mipengine/mip-extensions-platform#24]
目前[《MIP个性化组件提交规范》](https://github.com/mipengine/mip-extensions-platform/wiki/MIP%E4%B8%AA%E6%80%A7%E5%8C%96%E7%BB%84%E4%BB%B6%E6%8F%90%E4%BA%A4%E8%A7%84%E8%8C%83)规定:

>1.2 不应该使用外链JS （SHOULD NOT）
为了更好的页面性能，不建议以外链的方式引入JS。开发者本站维护的脚本必须封装为组件或AMD方式引入。广告，第三方统计等JS，请在代码注释中说明用途及服务提供商。未来会上线第三方JS引入机制，新机制上线后不允许引用更多外链JS。

解读为：
> 广告&统计等第三方提供的JS可以外链，站长自己的JS需要使用AMD require方式引用。

但带来以下问题：
### 1. 代码不能通过fecs
各站编码规范不统一，不能顺滑通过[fecs校验](http://fecs.baidu.com/demo), 不符合组件提交标准。
### 2. 多个组件引用通用库
mip-xx-A 和 mip-xx-B 都引用由自己维护的 common.js通用库，目前只能将common.js 复制两份，放在两个组件中，不便于维护。

关于这点，请大家提出自己的意见及解决方法。

**Comment by wyc3146** [comment]
我们有一个图标项目有几万行代码，如果不用外链JS的方式引入，要通过fecs校验几乎每行都要修改，代价太大了吧。

**Comment by jennyliang220** [comment]
之前看过AMP的一个showcase，类似数据表单绘制、点击交互的操作是写在amp-iframe里面的。如果是可控区域内的复交互，也可以使用iframe解决方案，内嵌https页面。但iframe需要限制宽高，防止全页面使用iframe引入。

**Comment by wyc3146** [comment]
图表js主要是用h5绘制k线图和分时图，根据各种数据计算绘制指标，还有一些如k线图放大缩小的交互。如果以AMD方式引入，所有的js代码都要通过fecs校验，实在是难搞。我之前花了一天时间，就改了一千多行，放弃了

**Comment by xuexb** [comment]
![image](https://user-images.githubusercontent.com/3872051/33058263-be5a54d4-cec9-11e7-9fcf-2902e57290cd.png)

---

**个人看法：**

加载依赖的库或者业务公用文件（以下统称 lib ），一般以下方式：

### 依赖文件放在组件文件夹并 AMD 化

主要因素：

1. 代码不规范
    1. 多人协作的代码 - 可能多人协作完成的代码
    2. 代码改造成本大 - 由于公司可能有公司自身的规范，而通常 lib 体积比较大，改动成本也较大
    3. 风格不一致 - 代码改造成功后在组件内维护，但可能存在和站长站内自身维护的 lib 风格有差异，导致维护成本增加
    4. 不太了解 `fecs format` 自动化格式 - `fecs format` 是一种代码格式化工具，可以相对的把代码格式大体的修正，但肯定还是需要手动的修复一些问题，附 [fecs api 文档](http://fecs.baidu.com/api) 。
1. 维护问题
    1. 上线繁琐 - 每次 lib 的修改需要上线组件
    2. 多组件引用  - 需要有类似 `mip-xxx-common-lib` 之类的组件，并且需要跨组件引用，总不能一个组件引用一个 lib 吧。
    3. 同步问题 - 由于站长站内还有 lib ，可能会遇到上线同步、生效同步等问题。
3. 完全问题 - 站长是否愿意把自身站点 lib 放在开源 github 中。

### 依赖文件以外链形式加载

主要因素：

1. 代码不可控 - 由于没有 code review 机制，代码不受任何约束，可能存在影响整个结果页的风险。
1. 不能保证速度 - 没有通过 MIP Cache 服务，不能针对性的 DNS 预取和全 MIP 站生效（如用户在mip-a站访问加载了组件a，那么在mip-b站时直接使用浏览器缓存，更加的快），并且依赖文件源的速度将直接影响组件加载，甚至影响整个页面加载。当然可能站长自己也有 CDN 静态缓存。
1. 不利于优化 - 目前线上运行是单个组件内文件合并加载，后续可以做整个页面的 `组件.js` 合并加载，这将大大的减少整个页面请求数，从而再加速。如果有外链的文件肯定会影响这个环节。

**Comment by momofan** [comment]
mip 组件机制的原则：当前组件 JS 脚本只为当前组件容器服务，不处理组件以外的 dom 和交互。
组件 js 的代码规范：需要强制 fecs，保持代码库的代码风格的一致性。
外链 js 的引用原则：可以引用当前组件依赖的库文件，例如：echarts，库文件只提供功能 api，不操作页面 dom。库文件可以保留原始代码风格，或者直接使用压缩后的代码。
