### ISSUE TITLE
组件审核平台能否添加账号登陆功能？

### ISSUE THREAD

**Issue by yvoooneguo** [mipengine/mip-extensions-platform#25]
目前组件审核平台一点登陆就直接进入到当前的百度账号了，但有的时候一个开发者开发多个网站，百度账号和我存组件的百度账号不是一个，这就导致了操作上的冲突，需要来回切换很麻烦。

**Comment by schoeu** [comment]
首先感谢你的反馈，对于组件审核平台账号这块暂时计划是接入github账号体系，可以解决你的部分问题。对于是否实现切换多个百度账号来满足此类需求，组内在评审下~
