### ISSUE TITLE
github中的组件迁移到mip组件审核平台

### ISSUE THREAD

**Issue by hejieye** [mipengine/mip-extensions-platform#86]
之前用github提交的组件希望能够迁移到mip的组件审核平台。
百度账号是18126205921， 希望能把https://github.com/mipengine/mip-extensions-platform中的
mip-iask-ajax、mip-iask-business、mip-iask-ext、mip-iask-report 这4个组件迁移到https://www.mipengine.org/platform/mip#/extensions 平台中去，谢谢！

**Comment by VenyXiong** [comment]
操作完毕，请登录18126205921 重新提交这几个组件即可~
