### ISSUE TITLE
有关组件审核

### ISSUE THREAD

**Issue by Tomqing** [mipengine/mip-extensions-platform#94]
站长开发组件有时候确实没有按照百度规定的来开发，往往会有这样或者那样的问题。
审核的时候能否一次把所有问题都列出来呢？
比如上传一个组件，这次是这个问题，下次又换了个问题，再下次......
这样很影响开发进度的呀。
当然，如果这样的话，审核难度也确实会增大，工时也会延长，大家也都理解。
这个有什么办法能够解决吗？

**Comment by Tomqing** [comment]
能不能整个即时修正方案，比如有些

**Comment by nocodeempire** [comment]
就不能实现自动化审核么, 非要人工去一条条查, 浪费资源浪费时间.

**Comment by zoumiaojiang** [comment]
现在所有的审核都会统一的走到 github 的 pr 进行审核，审核的人员会尽量一次将所有的问题都提出来，也请关注自己 pr 的状态，及时更新代码，以免耽误项目进度。
